favorite_places = ['majorca', 'medellin', 'malmo', 'accra', 'seoul']
print('Regular order ' , favorite_places)
print('Sorted order: ' , sorted(favorite_places))
print('Show that it is not changed ' , favorite_places)
print('Sorted in reverse order: ' , sorted(favorite_places, reverse=True))
print('Show that it is not changed: ' , favorite_places)
favorite_places.reverse()
print('Show list in reverse: ' , favorite_places)
favorite_places.reverse()
print('Show list in reverse: ' , favorite_places)
favorite_places.sort()
print('Show list with sort: ' , favorite_places)
favorite_places.sort(reverse=True)
print('Show list with sort in reverse: ' , favorite_places)
